// <auto-generated />
using System;
using Adeeb.Modules.Vocabulary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.Vocabulary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    [Migration("20260717100950_HardenVocabularySessionConcurrency")]
    partial class HardenVocabularySessionConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vocabulary")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NameTg")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_tg");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_vocabulary_languages_code");

                    b.ToTable("languages", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.StudentVocabularyCourse", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("StudentId")
                        .HasName("pk_student_vocabulary_courses");

                    b.HasIndex("LanguageId");

                    b.ToTable("student_courses", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.StudentWordProgress", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTimeOffset?>("LastPracticedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced_at_utc");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("integer")
                        .HasColumnName("mastery_level");

                    b.Property<DateOnly?>("NextReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("next_review_date");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("StudentId", "WordId")
                        .HasName("pk_student_word_progress");

                    b.HasIndex("WordId");

                    b.HasIndex("StudentId", "NextReviewDate");

                    b.ToTable("student_word_progress", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyDailyWord", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_automatic");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("LanguageId", "LocalDate")
                        .HasName("pk_vocabulary_daily_words");

                    b.HasIndex("WordId");

                    b.ToTable("daily_words", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CorrectTokenIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_token_index");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PromptRu")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt_ru");

                    b.Property<string>("PromptTarget")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt_target");

                    b.Property<string>("PromptTg")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt_tg");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordId", "Type", "Status");

                    b.ToTable("questions", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CorrectOrder")
                        .HasColumnType("integer")
                        .HasColumnName("correct_order");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("ValueRu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_ru");

                    b.Property<string>("ValueTarget")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_target");

                    b.Property<string>("ValueTg")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_tg");

                    b.Property<Guid?>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("question_options", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RelatedWordId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_word_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("RelatedWordId");

                    b.HasIndex("WordId", "RelatedWordId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_vocabulary_relations_word_related_type");

                    b.ToTable("relations", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("StudentId", "LanguageId", "Mode")
                        .IsUnique()
                        .HasDatabaseName("ix_vocabulary_sessions_student_mode_status")
                        .HasFilter("status = 'InProgress'");

                    b.ToTable("sessions", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySessionAnswer", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at_utc");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("SubmissionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("submission_json");

                    b.HasKey("SessionId", "QuestionId")
                        .HasName("pk_vocabulary_session_answers");

                    b.ToTable("session_answers", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySessionQuestion", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("CorrectAnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answer_json");

                    b.Property<int?>("CorrectTokenIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_token_index");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("SessionId", "QuestionId");

                    b.HasIndex("SessionId", "Order")
                        .IsUnique();

                    b.ToTable("session_questions", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionRu")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_ru");

                    b.Property<string>("DescriptionTg")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description_tg");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NameTg")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name_tg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "Level", "Status");

                    b.ToTable("topics", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExampleRu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("example_ru");

                    b.Property<string>("ExampleTarget")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("example_target");

                    b.Property<string>("ExampleTg")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("example_tg");

                    b.Property<string>("ExplanationRu")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation_ru");

                    b.Property<string>("ExplanationTg")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation_tg");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("normalized_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("target_text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("TranslationRu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("translation_ru");

                    b.Property<string>("TranslationTg")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("translation_tg");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "NormalizedText")
                        .IsUnique()
                        .HasDatabaseName("ux_vocabulary_words_language_normalized_text");

                    b.HasIndex("TopicId", "Level", "Status");

                    b.ToTable("words", "vocabulary");
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.StudentVocabularyCourse", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.StudentWordProgress", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyDailyWord", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestion", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestionOption", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyRelation", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("RelatedWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySession", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySessionAnswer", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularySessionQuestion", null)
                        .WithOne()
                        .HasForeignKey("Adeeb.Modules.Vocabulary.Domain.VocabularySessionAnswer", "SessionId", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularySessionQuestion", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularySession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyTopic", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyWord", b =>
                {
                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.LearningLanguage", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Vocabulary.Domain.VocabularyTopic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Vocabulary.Domain.VocabularyQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
