// <auto-generated />
using System;
using Adeeb.Modules.Students.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.Students.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20260724061127_HardenStudentEducationCatalog")]
    partial class HardenStudentEducationCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("students")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.AcademicYearRollover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcademicYearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_end");

                    b.Property<int>("AcademicYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_start");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("integer")
                        .HasColumnName("conflict_count");

                    b.Property<DateTimeOffset?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<Guid?>("ExecutedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by_user_id");

                    b.Property<int>("GraduatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("graduated_count");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("PreviewCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preview_created_at_utc");

                    b.Property<int>("PromotedCount")
                        .HasColumnType("integer")
                        .HasColumnName("promoted_count");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_academic_year_rollovers_idempotency");

                    b.HasIndex("AcademicYearStart", "AcademicYearEnd")
                        .IsUnique()
                        .HasDatabaseName("UX_academic_year_rollovers_year");

                    b.ToTable("academic_year_rollovers", "students", t =>
                        {
                            t.HasCheckConstraint("CK_academic_year_rollovers_year", "academic_year_end = academic_year_start + 1");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.AcademicYearRolloverItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("ProfileVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_version");

                    b.Property<string>("Reason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RolloverId")
                        .HasColumnType("uuid")
                        .HasColumnName("rollover_id");

                    b.Property<short?>("SourceGrade")
                        .HasColumnType("smallint")
                        .HasColumnName("source_grade");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("RolloverId", "StudentId")
                        .IsUnique();

                    b.ToTable("academic_year_rollover_items", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.EducationImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreatedRegions")
                        .HasColumnType("integer")
                        .HasColumnName("created_regions");

                    b.Property<int>("CreatedSchools")
                        .HasColumnType("integer")
                        .HasColumnName("created_schools");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_rows");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("SkippedSchools")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_schools");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text")
                        .HasColumnName("summary_json");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer")
                        .HasColumnName("valid_rows");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "CreatedAtUtc");

                    b.ToTable("education_import_batches", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("FullPathRu")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("full_path_ru");

                    b.Property<string>("FullPathTg")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("full_path_tg");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NameTg")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name_tg");

                    b.Property<string>("NormalizedNameRu")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_name_ru");

                    b.Property<string>("NormalizedNameTg")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_name_tg");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.PrimitiveCollection<Guid[]>("PathIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("path_ids");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PathIds");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PathIds"), "gin");

                    b.HasIndex("Type", "NormalizedNameRu")
                        .IsUnique()
                        .HasDatabaseName("UX_regions_root_type_name_ru")
                        .HasFilter("parent_id IS NULL AND is_active = true");

                    b.HasIndex("Type", "NormalizedNameTg")
                        .IsUnique()
                        .HasDatabaseName("UX_regions_root_type_name_tg")
                        .HasFilter("parent_id IS NULL AND is_active = true");

                    b.HasIndex("ParentId", "Type", "NormalizedNameRu")
                        .IsUnique()
                        .HasDatabaseName("UX_regions_parent_type_name_ru")
                        .HasFilter("parent_id IS NOT NULL AND is_active = true");

                    b.HasIndex("ParentId", "Type", "NormalizedNameTg")
                        .IsUnique()
                        .HasDatabaseName("UX_regions_parent_type_name_tg")
                        .HasFilter("parent_id IS NOT NULL AND is_active = true");

                    b.ToTable("regions", "students", t =>
                        {
                            t.HasCheckConstraint("CK_regions_depth_non_negative", "depth >= 0");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressText")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address_text");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("archived_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("MergedIntoSchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_school_id");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NameTg")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name_tg");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("search_text");

                    b.Property<string>("ShortName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("short_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoSchoolId");

                    b.HasIndex("RegionId", "NormalizedName", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_schools_region_name_type_live")
                        .HasFilter("number IS NULL AND status IN (0, 1, 2)");

                    b.HasIndex("RegionId", "Number", "Type")
                        .IsUnique()
                        .HasDatabaseName("UX_schools_region_number_type_live")
                        .HasFilter("number IS NOT NULL AND status IN (0, 1, 2)");

                    b.HasIndex("RegionId", "Status", "Number");

                    b.ToTable("schools", "students", t =>
                        {
                            t.HasCheckConstraint("CK_schools_number_positive", "number IS NULL OR number > 0");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.SchoolSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressText")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address_text");

                    b.Property<Guid?>("ApprovedSchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_school_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_admin_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmittedByStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_student_id");

                    b.Property<string>("SuggestedName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("suggested_name");

                    b.Property<int?>("SuggestedNumber")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_number");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedSchoolId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SubmittedByStudentId", "RegionId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_school_suggestions_pending_student_name")
                        .HasFilter("status = 0");

                    b.ToTable("school_suggestions", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.StudentEducationAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("new_values_json");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("old_values_json");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("resource_type");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "CreatedAtUtc");

                    b.HasIndex("ResourceType", "ResourceId", "CreatedAtUtc");

                    b.ToTable("student_education_audit_logs", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.StudentEducationProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int?>("AcademicYearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_end");

                    b.Property<int?>("AcademicYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_start");

                    b.Property<string>("AddressText")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address_text");

                    b.Property<short?>("CurrentGrade")
                        .HasColumnType("smallint")
                        .HasColumnName("current_grade");

                    b.Property<int?>("ExpectedGraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("expected_graduation_year");

                    b.Property<DateTimeOffset?>("GraduatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graduated_at_utc");

                    b.Property<Guid?>("PendingSchoolSuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_school_suggestion_id");

                    b.Property<DateTimeOffset?>("ProfileCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_completed_at_utc");

                    b.Property<Guid?>("ResidenceRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("residence_region_id");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("StudentId");

                    b.HasIndex("PendingSchoolSuggestionId");

                    b.HasIndex("ResidenceRegionId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_student_education_profiles_student");

                    b.ToTable("student_education_profiles", "students", t =>
                        {
                            t.HasCheckConstraint("CK_student_education_profiles_grade", "current_grade IS NULL OR (current_grade >= 1 AND current_grade <= 11)");

                            t.HasCheckConstraint("CK_student_education_profiles_year", "academic_year_start IS NULL OR academic_year_end = academic_year_start + 1");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.StudentSchoolEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcademicYearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_end");

                    b.Property<int>("AcademicYearStart")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year_start");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("change_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_student_school_enrollments_current_student")
                        .HasFilter("is_current = true");

                    b.HasIndex("Grade", "AcademicYearStart", "AcademicYearEnd");

                    b.HasIndex("RegionId", "AcademicYearStart", "AcademicYearEnd");

                    b.HasIndex("SchoolId", "AcademicYearStart", "AcademicYearEnd");

                    b.HasIndex("StudentId", "AcademicYearStart", "AcademicYearEnd");

                    b.ToTable("student_school_enrollments", "students", t =>
                        {
                            t.HasCheckConstraint("CK_student_school_enrollments_grade", "grade >= 1 AND grade <= 11");

                            t.HasCheckConstraint("CK_student_school_enrollments_year", "academic_year_end = academic_year_start + 1");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<int>("OnboardingState")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_students_identity_user_id");

                    b.ToTable("students", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.StudentDailyActivity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("StudentId", "LocalDate")
                        .HasName("PK_student_daily_activities");

                    b.ToTable("student_daily_activities", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<short?>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("grade");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("region");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("school_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("StudentId");

                    b.ToTable("student_profiles", "students");
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.AcademicYearRolloverItem", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.AcademicYearRollover", null)
                        .WithMany()
                        .HasForeignKey("RolloverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.Region", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.Region", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.School", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.School", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoSchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Adeeb.Modules.Students.Domain.Education.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.SchoolSuggestion", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.School", null)
                        .WithMany()
                        .HasForeignKey("ApprovedSchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Adeeb.Modules.Students.Domain.Education.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Students.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.StudentEducationProfile", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.SchoolSuggestion", null)
                        .WithMany()
                        .HasForeignKey("PendingSchoolSuggestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Adeeb.Modules.Students.Domain.Education.Region", null)
                        .WithMany()
                        .HasForeignKey("ResidenceRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Adeeb.Modules.Students.Domain.Education.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Adeeb.Modules.Students.Domain.Students.Student", null)
                        .WithOne()
                        .HasForeignKey("Adeeb.Modules.Students.Domain.Education.StudentEducationProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Education.StudentSchoolEnrollment", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Education.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Students.Domain.Education.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Students.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.StudentDailyActivity", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.StudentProfile", b =>
                {
                    b.HasOne("Adeeb.Modules.Students.Domain.Students.Student", null)
                        .WithOne("Profile")
                        .HasForeignKey("Adeeb.Modules.Students.Domain.Students.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Students.Domain.Students.Student", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
