// <auto-generated />
using System;
using Adeeb.Modules.Progression.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.Progression.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProgressionDbContext))]
    [Migration("20260721131927_InitialProgression")]
    partial class InitialProgression
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("progression")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("MaxLifetimeXpUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("max_lifetime_xp_units");

                    b.Property<long>("MinLifetimeXpUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("min_lifetime_xp_units");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ru");

                    b.Property<string>("NameTg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_tg");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_progression_leagues_order_active")
                        .HasFilter("status = 1");

                    b.ToTable("league_definitions", "progression", t =>
                        {
                            t.HasCheckConstraint("ck_progression_leagues_range", "min_lifetime_xp_units >= 0 AND (max_lifetime_xp_units IS NULL OR max_lifetime_xp_units > min_lifetime_xp_units)");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("integer")
                        .HasColumnName("final_rank");

                    b.Property<long>("InitialLifetimeXpUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("initial_lifetime_xp_units");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<DateTimeOffset?>("LastScoreAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_score_at_utc");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<long>("SeasonScoreUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("season_score_units");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_progression_memberships_season_user");

                    b.HasIndex("SeasonId", "LeagueId", "SeasonScoreUnits", "LastScoreAtUtc", "UserId")
                        .HasDatabaseName("ix_progression_memberships_leaderboard");

                    b.ToTable("league_memberships", "progression");
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueMovementResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FinalRank")
                        .HasColumnType("integer")
                        .HasColumnName("final_rank");

                    b.Property<Guid>("FromLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_league_id");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("ToLeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_league_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_progression_movements_season_user");

                    b.ToTable("league_movement_results", "progression");
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueScoreEvent", b =>
                {
                    b.Property<Guid>("LedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<int>("AmountUnits")
                        .HasColumnType("integer")
                        .HasColumnName("amount_units");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("LedgerEntryId")
                        .HasName("pk_progression_score_events_ledger");

                    b.HasIndex("MembershipId");

                    b.ToTable("league_score_events", "progression");
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoStartNext")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_start_next");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("configuration_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_progression_seasons_active")
                        .HasFilter("status = 1");

                    b.ToTable("league_seasons", "progression");
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueMembership", b =>
                {
                    b.HasOne("Adeeb.Modules.Progression.Domain.LeagueDefinition", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Progression.Domain.LeagueSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.Progression.Domain.LeagueScoreEvent", b =>
                {
                    b.HasOne("Adeeb.Modules.Progression.Domain.LeagueMembership", null)
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
