// <auto-generated />
using System;
using Adeeb.Modules.QuestionBank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.QuestionBank.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuestionBankDbContext))]
    [Migration("20260713154328_EstablishQuestionBankModelSnapshot")]
    partial class EstablishQuestionBankModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("question_bank")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder");

                    b.ToTable("answer_options", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOptionTranslation", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_option_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("MatchPairText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("match_pair_text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("AnswerOptionId", "Language");

                    b.ToTable("answer_option_translations", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Status");

                    b.HasIndex("TopicId", "Status");

                    b.HasIndex("Type", "Difficulty", "Status");

                    b.ToTable("questions", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.QuestionTranslation", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.HasKey("QuestionId", "Language");

                    b.ToTable("question_translations", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.Question", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOptionTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.AnswerOption", null)
                        .WithMany("Translations")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.QuestionTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.Question", null)
                        .WithMany("Translations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
