// <auto-generated />
using System;
using Adeeb.Modules.QuestionBank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.QuestionBank.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuestionBankDbContext))]
    [Migration("20260720151815_RefactorGlobalXpFoundation")]
    partial class RefactorGlobalXpFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("question_bank")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder");

                    b.ToTable("answer_options", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOptionTranslation", b =>
                {
                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_option_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("MatchPairText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("match_pair_text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("AnswerOptionId", "Language");

                    b.ToTable("answer_option_translations", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Status");

                    b.HasIndex("TopicId", "Status");

                    b.HasIndex("Type", "Difficulty", "Status");

                    b.ToTable("questions", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.QuestionTranslation", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.HasKey("QuestionId", "Language");

                    b.ToTable("question_translations", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.StudentRedListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("integer")
                        .HasColumnName("correct_streak");

                    b.Property<DateTimeOffset>("LastPracticedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced_at_utc");

                    b.Property<DateTimeOffset>("LastWrongAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_wrong_at_utc");

                    b.Property<DateTimeOffset?>("MasteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mastered_at_utc");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("question_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastPracticedAtUtc");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_red_list_user_question");

                    b.HasIndex("UserId", "Status", "SubjectId");

                    b.ToTable("student_red_list_items", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("MonthlyWindowKey")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("monthly_window_key");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "Mode", "MonthlyWindowKey")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_monthly_window")
                        .HasFilter("monthly_window_key IS NOT NULL");

                    b.ToTable("test_attempts", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_snapshot_json");

                    b.Property<DateTimeOffset>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at_utc");

                    b.Property<int?>("CorrectPairsCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_pairs_count");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_answered");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("TestAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_attempt_id");

                    b.Property<Guid>("TestAttemptQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_attempt_question_id");

                    b.Property<int?>("TotalPairsCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_pairs_count");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptId");

                    b.HasIndex("TestAttemptQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_attempt_answer_question");

                    b.ToTable("test_attempt_answers", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("question_snapshot_json");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("question_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TestAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_attempt_id");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_attempt_question_order");

                    b.HasIndex("TestAttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_attempt_question_identity");

                    b.ToTable("test_attempt_questions", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_snapshot_json");

                    b.Property<Guid>("TestAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_attempt_id");

                    b.Property<string>("TopicBreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("topic_breakdown_json");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_attempt_result");

                    b.ToTable("test_attempt_results", "question_bank");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestXpSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnswerXpUnits")
                        .HasColumnType("integer")
                        .HasColumnName("answer_xp_units");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<int>("CompletionBonusXpUnits")
                        .HasColumnType("integer")
                        .HasColumnName("completion_bonus_xp_units");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EasyCorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("easy_correct_count");

                    b.Property<int>("HardCorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("hard_correct_count");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_entry_id");

                    b.Property<int>("MediumCorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("medium_correct_count");

                    b.Property<int>("TotalXpUnits")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp_units");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_xp_settlement_attempt");

                    b.HasIndex("LedgerEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_xp_settlement_ledger");

                    b.ToTable("test_xp_settlements", "question_bank", t =>
                        {
                            t.HasCheckConstraint("ck_question_bank_xp_settlement_non_negative", "easy_correct_count >= 0 AND medium_correct_count >= 0 AND hard_correct_count >= 0 AND answer_xp_units >= 0 AND completion_bonus_xp_units >= 0 AND total_xp_units >= 0");

                            t.HasCheckConstraint("ck_question_bank_xp_settlement_total", "total_xp_units = answer_xp_units + completion_bonus_xp_units");

                            t.HasCheckConstraint("ck_question_bank_xp_settlement_zero_correct", "easy_correct_count + medium_correct_count + hard_correct_count > 0 OR total_xp_units = 0");
                        });
                });

            modelBuilder.Entity("Adeeb.SharedKernel.Progression.StudentXpBalance", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("TotalXpUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("total_xp_units");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId");

                    b.ToTable("student_xp_balances", "question_bank", t =>
                        {
                            t.HasCheckConstraint("ck_question_bank_xp_balance_non_negative", "total_xp_units >= 0");
                        });
                });

            modelBuilder.Entity("Adeeb.SharedKernel.Progression.XpLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountUnits")
                        .HasColumnType("integer")
                        .HasColumnName("amount_units");

                    b.Property<long>("BalanceAfterUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_units");

                    b.Property<long>("BalanceBeforeUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before_units");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_xp_ledger_idempotency");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_question_bank_xp_ledger_user_history");

                    b.HasIndex("UserId", "SourceType")
                        .HasDatabaseName("ix_question_bank_xp_ledger_user_source");

                    b.HasIndex("UserId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_bank_xp_ledger_source");

                    b.ToTable("xp_ledger_entries", "question_bank", t =>
                        {
                            t.HasCheckConstraint("ck_question_bank_xp_ledger_amount_non_negative", "amount_units >= 0");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.Question", null)
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOptionTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.AnswerOption", null)
                        .WithMany("Translations")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.QuestionTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.Question", null)
                        .WithMany("Translations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptAnswer", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.TestAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.TestAttemptQuestion", null)
                        .WithMany()
                        .HasForeignKey("TestAttemptQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptQuestion", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.TestAttempt", "TestAttempt")
                        .WithMany("Questions")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttemptResult", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.TestAttempt", null)
                        .WithOne("Result")
                        .HasForeignKey("Adeeb.Modules.QuestionBank.Domain.TestAttemptResult", "TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestXpSettlement", b =>
                {
                    b.HasOne("Adeeb.Modules.QuestionBank.Domain.TestAttempt", null)
                        .WithOne("XpSettlement")
                        .HasForeignKey("Adeeb.Modules.QuestionBank.Domain.TestXpSettlement", "AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.SharedKernel.Progression.XpLedgerEntry", null)
                        .WithOne()
                        .HasForeignKey("Adeeb.Modules.QuestionBank.Domain.TestXpSettlement", "LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.AnswerOption", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Adeeb.Modules.QuestionBank.Domain.TestAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Questions");

                    b.Navigation("Result");

                    b.Navigation("XpSettlement");
                });
#pragma warning restore 612, 618
        }
    }
}
