// <auto-generated />
using System;
using Adeeb.Modules.AcademicCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.AcademicCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AcademicCatalogDbContext))]
    [Migration("20260713154324_EstablishAcademicCatalogModelSnapshot")]
    partial class EstablishAcademicCatalogModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("academic")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status", "DisplayOrder");

                    b.ToTable("subjects", "academic");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.SubjectTranslation", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId", "Language");

                    b.ToTable("subject_translations", "academic");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Code")
                        .IsUnique();

                    b.HasIndex("SubjectId", "Status", "DisplayOrder");

                    b.ToTable("topics", "academic");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.TopicTranslation", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("TopicId", "Language");

                    b.ToTable("topic_translations", "academic");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.SubjectTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.AcademicCatalog.Domain.Subject", null)
                        .WithMany("Translations")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.Topic", b =>
                {
                    b.HasOne("Adeeb.Modules.AcademicCatalog.Domain.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.TopicTranslation", b =>
                {
                    b.HasOne("Adeeb.Modules.AcademicCatalog.Domain.Topic", null)
                        .WithMany("Translations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.Subject", b =>
                {
                    b.Navigation("Topics");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Adeeb.Modules.AcademicCatalog.Domain.Topic", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
