// <auto-generated />
using System;
using Adeeb.Modules.Mmt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adeeb.Modules.Mmt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MmtDbContext))]
    [Migration("20260714065717_AddMmtDataManagement")]
    partial class AddMmtDataManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mmt")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.AdmissionProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdmissionType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("admission_type");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("integer")
                        .HasColumnName("admission_year");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<Guid>("MmtClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("integer")
                        .HasColumnName("seats_count");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.Property<string>("StudyForm")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("study_form");

                    b.Property<string>("StudyLanguage")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("study_language");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("MmtClusterId", "AdmissionYear", "IsPublished", "IsActive")
                        .HasDatabaseName("ix_mmt_program_student_lookup");

                    b.HasIndex("UniversityId", "SpecialtyId", "MmtClusterId", "AdmissionType", "StudyForm", "StudyLanguage", "AdmissionYear")
                        .IsUnique()
                        .HasDatabaseName("ux_mmt_admission_program_identity");

                    b.ToTable("admission_programs", "mmt", t =>
                        {
                            t.HasCheckConstraint("ck_mmt_program_seats", "seats_count IS NULL OR seats_count >= 0");

                            t.HasCheckConstraint("ck_mmt_program_year", "admission_year >= 2000 AND admission_year <= 2100");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.MmtCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_mmt_clusters_code");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_mmt_clusters_active_name");

                    b.ToTable("clusters", "mmt");
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.PassingScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_program_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("numeric")
                        .HasColumnName("passing_score");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("integer")
                        .HasColumnName("seats_count");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionProgramId", "Year")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_mmt_score_latest");

                    b.ToTable("passing_score_history", "mmt", t =>
                        {
                            t.HasCheckConstraint("ck_mmt_score_seats", "seats_count IS NULL OR seats_count >= 0");

                            t.HasCheckConstraint("ck_mmt_score_value", "passing_score > 0 AND passing_score <= 1000 AND scale(passing_score) <= 2");

                            t.HasCheckConstraint("ck_mmt_score_year", "year >= 2000 AND year <= 2100");
                        });
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_mmt_specialties_code");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_mmt_specialties_active_name");

                    b.ToTable("specialties", "mmt");
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_url");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_full_name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("short_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFullName")
                        .IsUnique()
                        .HasDatabaseName("ux_mmt_universities_normalized_name");

                    b.HasIndex("IsActive", "FullName")
                        .HasDatabaseName("ix_mmt_universities_active_name");

                    b.ToTable("universities", "mmt");
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.AdmissionProgram", b =>
                {
                    b.HasOne("Adeeb.Modules.Mmt.Domain.MmtCluster", "MmtCluster")
                        .WithMany()
                        .HasForeignKey("MmtClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Mmt.Domain.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Adeeb.Modules.Mmt.Domain.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MmtCluster");

                    b.Navigation("Specialty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.PassingScoreHistory", b =>
                {
                    b.HasOne("Adeeb.Modules.Mmt.Domain.AdmissionProgram", "AdmissionProgram")
                        .WithMany("PassingScores")
                        .HasForeignKey("AdmissionProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdmissionProgram");
                });

            modelBuilder.Entity("Adeeb.Modules.Mmt.Domain.AdmissionProgram", b =>
                {
                    b.Navigation("PassingScores");
                });
#pragma warning restore 612, 618
        }
    }
}
