import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Archive, ArrowLeft, Award, CheckCircle2, History, ListChecks, RotateCcw, ShieldCheck, XCircle } from 'lucide-react'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { subjectsApi, subjectKeys } from '@/features/academic/api/subjects.api'
import { studentTestingApi, studentTestingKeys } from '@/features/student-testing/api/student-testing.api'
import { canStartRedList } from '@/features/student-testing/lib/student-testing'
import { RedListStatus, TestAttemptStatus, type RedListItemDto } from '@/features/student-testing/model/student-testing.types'
import { TestingBadge, TestingButton, TestingCard, TestingEmpty, TestingError, TestingLoading } from '@/features/student-testing/ui/TestingUi'
import { XpRewardSummary } from '@/features/student-testing/ui/XpRewardSummary'
import { StudentPageHeader } from '@/routes/student/StudentUi'
import { SelectField } from '@/shared/ui/SelectField'

function useSubjectNames() {
  const query = useQuery({ queryKey: subjectKeys.publicList({ page: 1, pageSize: 50, status: 1 }), queryFn: () => subjectsApi.publicList({ page: 1, pageSize: 50, status: 1 }) })
  return useMemo(() => Object.fromEntries((query.data?.items ?? []).map((subject) => [subject.id, subject.name])), [query.data])
}

function displayDate(value: string | null, language: string) { return value ? new Intl.DateTimeFormat(language, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—' }

export function TestResultPage() {
  const { attemptId = '' } = useParams(); const { t, i18n } = useTranslation(); const names = useSubjectNames()
  const result = useQuery({ queryKey: studentTestingKeys.result(attemptId), queryFn: () => studentTestingApi.getAttemptResult(attemptId), enabled: Boolean(attemptId) })
  const config = useQuery({ queryKey: studentTestingKeys.config(), queryFn: studentTestingApi.getTestingConfig })
  const redList = useQuery({ queryKey: studentTestingKeys.redListSummary(), queryFn: studentTestingApi.getRedListSummary })
  if (result.isLoading) return <TestingLoading />
  if (result.isError) return <TestingError error={result.error} onRetry={() => void result.refetch()} />
  if (!result.data) return null
  const data = result.data; const motivational = data.percentage >= 80 ? t('student.testing.result.good') : data.percentage >= 50 ? t('student.testing.result.improvable') : t('student.testing.result.workErrors')
  const redListReady = config.data && redList.data ? canStartRedList(redList.data.activeCount, config.data.redListMinimumQuestions) : false
  return <div className="grid gap-5"><Link to="/student/tests" className="inline-flex w-fit items-center gap-2 text-sm font-black text-[#5146f0]"><ArrowLeft className="h-4 w-4" />{t('student.testing.backToTests')}</Link><StudentPageHeader title={t('student.testing.result.title')} description={motivational} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={t('student.testing.result.score')} value={String(data.score)} /><Metric label={t('student.testing.result.percentage')} value={`${data.percentage}%`} /><Metric label={t('student.testing.result.correct')} value={String(data.correctCount)} tone="success" /><Metric label={t('student.testing.result.wrong')} value={String(data.wrongCount)} tone="danger" /></div>
    <XpRewardSummary data={data} language={i18n.language} />
    <div className="flex flex-wrap gap-3"><Link to="/student/tests/history" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--student-border)] px-4 text-sm font-black text-[var(--student-text)] no-underline"><History className="h-4 w-4" />{t('student.testing.history.title')}</Link>{redListReady ? <Link to="/student/tests/red-list" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#5146f0] px-4 text-sm font-black text-white no-underline"><ShieldCheck className="h-4 w-4" />{t('student.testing.redPractice.title')}</Link> : null}</div>
    {data.subjectBreakdown.length > 0 ? <TestingCard><h2 className="text-lg font-black">{t('student.testing.result.subjectBreakdown')}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{data.subjectBreakdown.map((item) => <BreakdownRow key={item.subjectId} title={names[item.subjectId] ?? t('student.testing.subjectUnknown')} correct={item.correct} total={item.total} percentage={item.percentage} />)}</div></TestingCard> : null}
    {data.topicBreakdown.length > 0 ? <TestingCard><h2 className="text-lg font-black">{t('student.testing.result.topicBreakdown')}</h2><div className="mt-4 grid gap-2">{data.topicBreakdown.map((item, index) => <BreakdownRow key={item.topicId ?? index} title={t('student.testing.result.topicNumber', { number: index + 1 })} correct={item.correct} total={item.total} percentage={item.total ? Math.round(item.correct * 100 / item.total) : 0} />)}</div></TestingCard> : null}
    {data.weakTopics.length > 0 ? <TestingCard><h2 className="text-lg font-black">{t('student.testing.result.weakTopics')}</h2><div className="mt-4 flex flex-wrap gap-2">{data.weakTopics.map((item, index) => <TestingBadge key={`${item.topicId}-${index}`} tone="warning">{names[item.subjectId] ?? t('student.testing.subjectUnknown')} · {item.percentage}%</TestingBadge>)}</div></TestingCard> : null}
    <TestingCard><div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><h2 className="text-lg font-black">{t('student.testing.result.review')}</h2><span className="text-xs text-[var(--student-muted)]">{displayDate(data.submittedAtUtc, i18n.language)}</span></div><div className="mt-4 divide-y divide-[var(--student-border)]">{data.answers.map((answer, index) => <details key={answer.questionId} className="group py-4"><summary className="flex cursor-pointer list-none items-start gap-3"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg ${answer.isCorrect ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{answer.isCorrect ? <CheckCircle2 className="h-4 w-4" /> : <XCircle className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{t('student.testing.questionNumber', { number: index + 1 })}</strong><span className="mt-1 block text-sm leading-6 text-[var(--student-muted)]">{answer.content}</span></span><TestingBadge tone={answer.isCorrect ? 'success' : 'danger'}>{answer.isCorrect ? t('student.testing.correct') : t('student.testing.wrong')}</TestingBadge></summary><div className="ml-11 mt-4 grid gap-3 rounded-lg bg-[var(--student-surface-soft)] p-4 text-sm"><ReviewValue label={t('student.testing.yourAnswer')} value={answer.userAnswer} /><ReviewValue label={t('student.testing.correctAnswer')} value={answer.correctAnswer} />{answer.explanation ? <ReviewValue label={t('student.testing.explanation')} value={answer.explanation} /> : null}{answer.totalPairsCount !== null ? <p><strong>{t('student.testing.result.matchingPairs')}:</strong> {answer.correctPairsCount}/{answer.totalPairsCount}</p> : null}</div></details>)}</div></TestingCard>
  </div>
}

export function TestHistoryPage() {
  const { t, i18n } = useTranslation(); const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('page')) || 1)
  const history = useQuery({ queryKey: studentTestingKeys.history({ page, pageSize: 10 }), queryFn: () => studentTestingApi.getTestingHistory({ page, pageSize: 10 }) })
  if (history.isLoading) return <TestingLoading />
  if (history.isError) return <TestingError error={history.error} onRetry={() => void history.refetch()} />
  if (!history.data) return <TestingLoading />
  const pages = Math.max(1, Math.ceil(history.data.totalCount / history.data.pageSize))
  return <div className="grid gap-5"><StudentPageHeader title={t('student.testing.history.title')} description={t('student.testing.history.description')} /><TestingCard>{history.data.items.length === 0 ? <TestingEmpty title={t('student.testing.history.empty')} /> : <div className="grid gap-3">{history.data.items.map((item) => { const hasResult = [TestAttemptStatus.submitted, TestAttemptStatus.autoSubmitted].includes(item.status as 2 | 3); return <article key={item.attemptId} className="flex flex-col gap-3 rounded-lg border border-[var(--student-border)] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{t(`student.testing.modes.${item.mode}`)}</strong><TestingBadge tone={hasResult ? 'success' : 'neutral'}>{t(`student.testing.statuses.${item.status}`)}</TestingBadge></div><p className="mt-2 text-sm text-[var(--student-muted)]">{displayDate(item.submittedAtUtc ?? item.startedAtUtc, i18n.language)} · {t('student.testing.history.questions', { count: item.questionCount })}</p></div><div className="flex flex-wrap items-center justify-between gap-3 sm:justify-end"><strong className="text-lg">{item.percentage}%</strong><span className={`inline-flex items-center gap-1 rounded-md px-2.5 py-1 text-sm font-black ${item.xpAwarded ? 'bg-amber-50 text-amber-700' : 'bg-[var(--student-surface-soft)] text-[var(--student-muted)]'}`}><Award className="h-4 w-4" />{item.xpAwarded ? '+' : ''}{new Intl.NumberFormat(i18n.language, { maximumFractionDigits: 1 }).format(item.totalXp)} XP</span>{hasResult ? <Link to={`/student/tests/attempts/${item.attemptId}/result`} className="text-sm font-black text-[#5146f0]">{t('student.testing.history.viewResult')}</Link> : null}</div></article> })}</div>}<Pagination page={page} pages={pages} onPage={(next) => setParams(next > 1 ? { page: String(next) } : {})} /></TestingCard></div>
}

export function StudentRedListPage() {
  const { t, i18n } = useTranslation(); const queryClient = useQueryClient(); const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('page')) || 1); const subjectId = params.get('subjectId') ?? ''; const status = Number(params.get('status')) || undefined
  const names = useSubjectNames(); const summary = useQuery({ queryKey: studentTestingKeys.redListSummary(), queryFn: studentTestingApi.getRedListSummary }); const config = useQuery({ queryKey: studentTestingKeys.config(), queryFn: studentTestingApi.getTestingConfig }); const listQuery = { page, pageSize: 10, ...(subjectId ? { subjectId } : {}), ...(status ? { status } : {}) }; const list = useQuery({ queryKey: studentTestingKeys.redList(listQuery), queryFn: () => studentTestingApi.getRedList(listQuery) })
  const action = useMutation({ mutationFn: ({ questionId, restore }: { questionId: string; restore: boolean }) => restore ? studentTestingApi.restoreRedListQuestion(questionId) : studentTestingApi.archiveRedListQuestion(questionId), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: studentTestingKeys.redListSummary() }), queryClient.invalidateQueries({ queryKey: studentTestingKeys.all })]) } })
  if (summary.isLoading || config.isLoading || list.isLoading) return <TestingLoading />
  if (summary.isError) return <TestingError error={summary.error} onRetry={() => void summary.refetch()} />
  if (config.isError) return <TestingError error={config.error} onRetry={() => void config.refetch()} />
  if (list.isError) return <TestingError error={list.error} onRetry={() => void list.refetch()} />
  if (!summary.data || !config.data || !list.data) return <TestingLoading />
  const ready = canStartRedList(summary.data.activeCount, config.data.redListMinimumQuestions); const pages = Math.max(1, Math.ceil(list.data.totalCount / list.data.pageSize)); const subjectOptions = summary.data.subjects.map((item) => ({ value: item.subjectId, label: names[item.subjectId] ?? t('student.testing.subjectUnknown') }))
  function update(next: { subjectId?: string; status?: string; page?: number }) { const values = new URLSearchParams(params); Object.entries(next).forEach(([key, value]) => { if (!value || value === '0' || (key === 'page' && value === 1)) values.delete(key); else values.set(key, String(value)) }); if ('subjectId' in next || 'status' in next) values.delete('page'); setParams(values) }
  return <div className="grid gap-5"><StudentPageHeader title={t('student.testing.redList.title')} description={t('student.testing.redList.description')} /><div className="grid grid-cols-3 gap-3"><Metric label={t('student.testing.redList.active')} value={String(summary.data.activeCount)} tone="warning" /><Metric label={t('student.testing.redList.mastered')} value={String(summary.data.masteredCount)} tone="success" /><Metric label={t('student.testing.redList.archived')} value={String(summary.data.archivedCount)} /></div><div>{ready ? <Link to="/student/tests/red-list" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#5146f0] px-4 text-sm font-black text-white no-underline"><ListChecks className="h-4 w-4" />{t('student.testing.redPractice.title')}</Link> : <p className="rounded-lg bg-amber-50 p-4 text-sm font-bold text-amber-800">{t('student.testing.redPractice.locked', { minimum: config.data.redListMinimumQuestions, count: summary.data.activeCount })}</p>}</div><TestingCard><div className="grid gap-3 sm:grid-cols-2"><SelectField value={subjectId} onValueChange={(value) => update({ subjectId: value })} placeholder={t('student.testing.redList.allSubjects')} options={[{ value: '', label: t('student.testing.redList.allSubjects') }, ...subjectOptions]} className="[&_button]:min-h-11 [&_button]:rounded-lg [&_button]:border [&_button]:border-[var(--student-border)] [&_button]:py-2 [&_button]:text-sm" /><SelectField value={status ? String(status) : ''} onValueChange={(value) => update({ status: value })} placeholder={t('student.testing.redList.allStatuses')} options={[{ value: '', label: t('student.testing.redList.allStatuses') }, { value: '1', label: t('student.testing.redList.active') }, { value: '2', label: t('student.testing.redList.mastered') }, { value: '3', label: t('student.testing.redList.archived') }]} className="[&_button]:min-h-11 [&_button]:rounded-lg [&_button]:border [&_button]:border-[var(--student-border)] [&_button]:py-2 [&_button]:text-sm" /></div>{list.data.items.length === 0 ? <div className="mt-5"><TestingEmpty title={t('student.testing.redList.empty')} /></div> : <div className="mt-5 grid gap-3">{list.data.items.map((item) => <RedListRow key={item.id} item={item} subjectName={names[item.subjectId]} language={i18n.language} pending={action.isPending} onAction={(restore) => action.mutate({ questionId: item.questionId, restore })} />)}</div>}<Pagination page={page} pages={pages} onPage={(next) => update({ page: next })} /></TestingCard></div>
}

function RedListRow({ item, subjectName, language, pending, onAction }: { item: RedListItemDto; subjectName: string | undefined; language: string; pending: boolean; onAction: (restore: boolean) => void }) { const { t } = useTranslation(); const archived = item.status === RedListStatus.archived; return <article className="rounded-lg border border-[var(--student-border)] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><TestingBadge tone={archived ? 'neutral' : item.status === RedListStatus.mastered ? 'success' : 'warning'}>{t(`student.testing.redList.statuses.${item.status}`)}</TestingBadge><span className="text-xs font-bold text-[var(--student-muted)]">{subjectName ?? t('student.testing.subjectUnknown')}</span></div><h2 className="mt-3 text-sm font-black leading-6">{item.questionContent}</h2><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-[var(--student-muted)]"><span>{t('student.testing.redList.wrongCount')}: {item.wrongCount}</span><span>{t('student.testing.redList.streak')}: {item.correctStreak}/3</span><span>{t('student.testing.redList.lastWrong')}: {displayDate(item.lastWrongAtUtc, language)}</span><span>{t('student.testing.redList.lastPractice')}: {displayDate(item.lastPracticedAtUtc, language)}</span></div></div><TestingButton variant="secondary" disabled={pending} onClick={() => onAction(archived)}>{archived ? <RotateCcw className="h-4 w-4" /> : <Archive className="h-4 w-4" />}{archived ? t('student.testing.redList.restore') : t('student.testing.redList.archive')}</TestingButton></div></article> }
function Metric({ label, value, tone = 'neutral' }: { label: string; value: string; tone?: 'neutral' | 'success' | 'danger' | 'warning' }) { const colors = { neutral: 'text-[#5146f0]', success: 'text-emerald-700', danger: 'text-red-700', warning: 'text-amber-700' }; return <TestingCard className="min-w-0"><p className="truncate text-xs font-bold text-[var(--student-muted)]">{label}</p><p className={`mt-2 text-2xl font-black sm:text-3xl ${colors[tone]}`}>{value}</p></TestingCard> }
function BreakdownRow({ title, correct, total, percentage }: { title: string; correct: number; total: number; percentage: number }) { return <div className="rounded-lg bg-[var(--student-surface-soft)] p-4"><div className="flex justify-between gap-3 text-sm"><strong className="truncate">{title}</strong><span className="font-black">{percentage}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[var(--student-border)]"><span className="block h-full bg-[#5146f0]" style={{ width: `${Math.min(100, percentage)}%` }} /></div><p className="mt-2 text-xs text-[var(--student-muted)]">{correct}/{total}</p></div> }
function ReviewValue({ label, value }: { label: string; value: string | null }) { const { t } = useTranslation(); return <p><strong>{label}:</strong> <span className="text-[var(--student-muted)]">{value || t('student.testing.noAnswer')}</span></p> }
function Pagination({ page, pages, onPage }: { page: number; pages: number; onPage: (page: number) => void }) { const { t } = useTranslation(); if (pages <= 1) return null; return <div className="mt-5 flex items-center justify-end gap-2"><span className="mr-2 text-xs font-black text-[var(--student-muted)]">{page}/{pages}</span><TestingButton variant="secondary" className="h-10 min-h-10 w-10 px-0" disabled={page <= 1} onClick={() => onPage(page - 1)} aria-label={t('student.previousPage')}><ArrowLeft className="h-4 w-4" /></TestingButton><TestingButton variant="secondary" className="h-10 min-h-10 w-10 px-0" disabled={page >= pages} onClick={() => onPage(page + 1)} aria-label={t('student.nextPage')}><ArrowLeft className="h-4 w-4 rotate-180" /></TestingButton></div> }
